config { type: "table" }

-- select date_trunc(date, MONTH) as mon
--         , airport_name
--         , avg(percent_of_baseline) as avg_percent_of_baseline
-- from ${ref("airport_traffic")}
-- where (date_trunc(date, MONTH) = '2020-08-01' 
--         or date_trunc(date, MONTH) = '2021-08-01')
--         and airport_name = 'Kingsford Smith'
-- group by mon
--         , airport_name
-- order by mon asc

select 
